# Generated by Django 4.2.7 on 2023-12-17 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import town.upload_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Объявления')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Объявления')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Объявления')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('text_ky', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('file', models.FileField(blank=True, upload_to='media/', verbose_name='Файл')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Файл')),
                ('file_ky', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Объявления',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер контакта')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('text', models.TextField(blank=True, verbose_name='Текст публикации')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('contact_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('message', models.TextField(max_length=455, verbose_name='Сообщение')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback_attachments/')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='История')),
                ('title_ru', models.CharField(max_length=40, null=True, verbose_name='История')),
                ('title_ky', models.CharField(max_length=40, null=True, verbose_name='История')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('text', models.TextField(blank=True, verbose_name='Текст[ru]')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст[ru]')),
                ('text_ky', models.TextField(blank=True, null=True, verbose_name='Текст[ru]')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История',
            },
        ),
        migrations.CreateModel(
            name='Mayor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('image', models.ImageField(upload_to=town.upload_image.upload_image, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Мэр города',
                'verbose_name_plural': 'Мэр города',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название новости')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название новости')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название новости')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('text', models.TextField(blank=True, verbose_name='Текст публикации')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('text_ky', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('image', models.ImageField(blank=True, upload_to=town.upload_image.upload_image, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='OfficialDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('text_ky', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('file', models.FileField(blank=True, upload_to='media/', verbose_name='Файл')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Файл')),
                ('file_ky', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Социальное и экономическое развитие',
                'verbose_name_plural': 'Социальное и экономическое развитие',
            },
        ),
        migrations.CreateModel(
            name='PassportOfTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('text_ky', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
            ],
            options={
                'verbose_name': 'Паспорт города',
                'verbose_name_plural': 'Паспорт города',
            },
        ),
        migrations.CreateModel(
            name='TownHallManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('first_name_ru', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('first_name_ky', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('last_name_ru', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('last_name_ky', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('middle_name_ru', models.CharField(max_length=50, null=True, verbose_name='Отчество')),
                ('middle_name_ky', models.CharField(max_length=50, null=True, verbose_name='Отчество')),
                ('position', models.CharField(max_length=120, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=120, null=True, verbose_name='Должность')),
                ('position_ky', models.CharField(max_length=120, null=True, verbose_name='Должность')),
                ('image', models.ImageField(upload_to=town.upload_image.upload_image, verbose_name='Изображение')),
                ('birth_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('education_ru', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('education_ky', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('work_experience', models.TextField(verbose_name='Опыт работы')),
                ('work_experience_ru', models.TextField(null=True, verbose_name='Опыт работы')),
                ('work_experience_ky', models.TextField(null=True, verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Руководитель мэрии',
                'verbose_name_plural': 'Руководители мэрии',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('text_ky', models.TextField(blank=True, null=True, verbose_name='Текст публикации')),
                ('file', models.FileField(blank=True, upload_to='media/', verbose_name='Файл')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Файл')),
                ('file_ky', models.FileField(blank=True, null=True, upload_to='media/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=town.upload_image.upload_image)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='town.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialDocumentsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=town.upload_image.upload_image)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='town.officialdocuments')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=town.upload_image.upload_image)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='town.news')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=town.upload_image.upload_image)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='town.history')),
            ],
        ),
    ]
