# pull official base image
FROM python:3.9.6-bullseye

# set work directory
WORKDIR /usr/src/My-town

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apt-get update \
    && apt-get install -y postgresql-server-dev-all gcc python3-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# Установка netcat
RUN apt-get update && apt-get install -y netcat

# copy entrypoint.sh
COPY ./entrypoint.prod.sh .
RUN apt-get update && apt-get install dos2unix -y
RUN dos2unix /usr/src/My-town/entrypoint.prod.sh \
    && chmod +x /usr/src/My-town/entrypoint.prod.sh


# create the appropriate directories
ENV HOME=/home/My-town
ENV APP_HOME=/home/My-town/web
RUN mkdir -p $HOME  # Создание родительской директории, если её нет
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/static
RUN mkdir $APP_HOME/media
WORKDIR $APP_HOME


# copy project
COPY . .

# run entrypoint.sh
ENTRYPOINT ["/usr/src/My-town/entrypoint.prod.sh"]
